# NSE Yahoo Finance tickers
NIFTY50 = [
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","ICICIBANK.NS","INFY.NS",
    "ITC.NS","BHARTIARTL.NS","LT.NS","SBIN.NS","AXISBANK.NS",
    "KOTAKBANK.NS","HINDUNILVR.NS","BAJFINANCE.NS","MARUTI.NS",
    "M&M.NS","SUNPHARMA.NS","TITAN.NS","ULTRACEMCO.NS","NTPC.NS",
    "POWERGRID.NS","TATASTEEL.NS","TATAMOTORS.NS","ADANIENT.NS",
    "ADANIPORTS.NS","HCLTECH.NS","WIPRO.NS","TECHM.NS","ASIANPAINT.NS",
    "NESTLEIND.NS","HINDALCO.NS","JSWSTEEL.NS","COALINDIA.NS",
    "ONGC.NS","BPCL.NS","IOC.NS","GRASIM.NS","CIPLA.NS","DRREDDY.NS",
    "EICHERMOT.NS","HEROMOTOCO.NS","BAJAJ-AUTO.NS","BRITANNIA.NS",
    "DIVISLAB.NS","APOLLOHOSP.NS","TRENT.NS","BEL.NS","SHRIRAMFIN.NS",
    "BAJAJFINSV.NS","INDUSINDBK.NS","TATACONSUM.NS"
]
